apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      nodePort: 31001
  selector:
    app: prometheus
    type: monitoring-tool
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---


apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus
spec:
    replicas: 1
    selector:
          matchLabels:
              app: prometheus
    template:
        metadata:
            name: prometheus
            labels:
                app: prometheus
                type: monitoring-tool
        spec:
            containers:
                - name: prometheus
                  image: vimal13/prometheus
                  volumeMounts: 
                      - name: prom-vol
                        mountPath: /prometheus
            volumes:
                - name: prom-vol
                  persistentVolumeClaim: 
                      claimName: prom-pvc